name: Python application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/cgohlke/talib-build/releases/download/v0.6.3/ta_lib-0.6.3-cp310-cp310-win_amd64.whl
        pip install vnpy ruff mypy uv
    - name: Lint with ruff
      run: |
        # Run ruff linter based on pyproject.toml configuration
        ruff check .
    - name: Type check with mypy
      run: |
        # Run mypy type checking based on pyproject.toml configuration
        mypy vnpy_dolphindb
    - name: Build packages with uv
      run: |
        # Build source distribution and wheel distribution
        uv build
